######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 9 14:10:44 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
