######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 9 14:33:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profile_widget.h
SOURCES += main.cpp profile_widget.cpp
